
services:
  streamlit-app:
    build: .
    container_name: aideom_vn_app
    ports:
      - "8501:8501"
    volumes:
      # Mount code directory để khi code thay đổi ở máy thật (hoặc VS Code), nó sẽ cập nhật vào container
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # Tự động khởi động lại container nếu có lỗi
    restart: unless-stopped
