import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import Plot from 'react-plotly.js';
import {Brain, BookOpen, SlidersHorizontal, AlertTriangle, LayoutDashboard, GitCompare, WalletCards} from 'lucide-react';
import './style.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8001/api';
const TABS = [
  ['overview','Tổng quan', LayoutDashboard],
  ['allocation','Phân bổ', WalletCards],
  ['scenarios','Kịch bản so sánh', GitCompare],
  ['risks','Cảnh báo rủi ro', AlertTriangle],
];
const fallbackLessons = Array.from({length:11}).map((_,i)=>({id:`lesson${String(i+1).padStart(2,'0')}`,title:`Bài ${i+1} - AIDEOM-VN`,description:'Demo offline',params:[{key:'budget',label:'Ngân sách',default:100,min:20,max:200,step:5}],module:'M'}));
const fallbackResult = (lesson) => ({lesson, tabs:{overview:{metrics:[{label:'KPI',value:82,unit:'điểm',status:'good'},{label:'AI index',value:0.48,unit:'',status:'neutral'},{label:'Risk',value:0.32,unit:'',status:'warning'}],chart:{labels:[2026,2027,2028,2029,2030],series:[{name:'KPI',data:[62,67,72,78,82]}]}},allocation:{title:'Phân bổ mẫu',chart:{labels:['NMM','RRD','NCC','CH','SE','MD'],series:[{name:'K/I',data:[10,14,11,9,16,10]},{name:'D',data:[8,18,10,7,20,9]},{name:'AI',data:[4,16,8,3,21,6]},{name:'H',data:[15,12,14,16,11,15]}]},table:{}},scenarios:{chart:{labels:[2026,2027,2028,2029,2030],series:[{name:'Cơ sở',data:[60,65,70,75,80]},{name:'AI nhanh',data:[62,69,76,83,90]},{name:'Bao trùm',data:[61,67,73,80,86]}]},summary:'Fallback demo khi backend chưa phản hồi.'},risks:{risk_score:.32,level:'low',alerts:['Backend chưa phản hồi, đang dùng dữ liệu demo.']}}});
function plotData(chart, type='bar') { if(!chart?.series) return []; return chart.series.map(s=>({x: chart.labels, y: s.data, type, mode: type==='scatter'?'lines+markers':undefined, name:s.name, marker:{}})); }
function Card({children, className=''}){ return <div className={`card ${className}`}>{children}</div> }
function Metric({m}){ return <div className={`metric ${m.status||''}`}><span>{m.label}</span><strong>{m.value} <small>{m.unit}</small></strong></div> }
function Params({lesson, params, setParams, onRun, loading}){ return <Card className="params"><div className="section-title"><SlidersHorizontal size={18}/> Tinh chỉnh hệ số mô hình</div>{(lesson?.params||[]).map(p=><label className="slider" key={p.key}><div><span>{p.label}</span><b>{params[p.key] ?? p.default}</b></div><input type="range" min={p.min} max={p.max} step={p.step} value={params[p.key] ?? p.default} onChange={e=>setParams(v=>({...v,[p.key]:Number(e.target.value)}))}/></label>)}<button className="primary" onClick={onRun}>{loading?'Đang chạy...':'Chạy'}</button></Card> }
function TabContent({tab, result}){ const data = result?.tabs?.[tab]; if(!data) return null; if(tab==='risks') return <div className="grid two"><Card><div className="section-title"><AlertTriangle size={18}/> Mức rủi ro</div><div className={`risk-badge ${data.level}`}>{data.level?.toUpperCase()} · {Math.round((data.risk_score||0)*100)}%</div><div className="riskbar"><i style={{width:`${Math.round((data.risk_score||0)*100)}%`}}/></div></Card><Card><div className="section-title">Danh sách cảnh báo</div>{(data.alerts||[]).map((a,i)=><p className="alert" key={i}>⚠️ {a}</p>)}</Card></div>;
 if(tab==='overview') return <><div className="metrics">{(data.metrics||[]).map((m,i)=><Metric key={i} m={m}/>)}</div><Card><Plot data={plotData(data.chart,'scatter')} layout={{height:360,margin:{t:30,l:40,r:20,b:40},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',legend:{orientation:'h'}}} config={{displayModeBar:false}} /></Card></>;
 return <div className="grid two"><Card><div className="section-title">{data.title||'Biểu đồ phân tích'}</div><Plot data={plotData(data.chart,'bar')} layout={{height:380,barmode:'group',margin:{t:20,l:40,r:20,b:60},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',legend:{orientation:'h'}}} config={{displayModeBar:false}} /></Card><Card><div className="section-title">Diễn giải nhanh</div><p className="muted">{data.summary || 'Kết quả được cập nhật theo bộ hệ số hiện tại. Có thể điều chỉnh slider bên phải và chạy lại để so sánh.'}</p><pre>{JSON.stringify(data.table || {}, null, 2).slice(0,1200)}</pre></Card></div> }
function App(){ const [lessons,setLessons]=useState(fallbackLessons); const [selected,setSelected]=useState('lesson01'); const [lesson,setLesson]=useState(fallbackLessons[0]); const [params,setParams]=useState({}); const [result,setResult]=useState(fallbackResult(fallbackLessons[0])); const [tab,setTab]=useState('overview'); const [loading,setLoading]=useState(false); const [online,setOnline]=useState(false);
 useEffect(()=>{fetch(`${API}/lessons/`).then(r=>r.json()).then(j=>{setLessons(j.lessons); setLesson(j.lessons[0]); setSelected(j.lessons[0].id); setOnline(true)}).catch(()=>setOnline(false))},[]);
 useEffect(()=>{const l=lessons.find(x=>x.id===selected)||lessons[0]; setLesson(l); const init={}; (l.params||[]).forEach(p=>init[p.key]=p.default); setParams(init); setResult(fallbackResult(l)); setTab('overview');},[selected, lessons]);
 const run=async()=>{setLoading(true); try{const r=await fetch(`${API}/lessons/${selected}/run/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({params})}); const j=await r.json(); setResult(j); setOnline(true)}catch(e){setResult(fallbackResult(lesson)); setOnline(false)} finally{setLoading(false)}};
 useEffect(()=>{ if(lesson?.id) run(); },[lesson?.id]);
 return <div className="app"><aside><div className="brand"><Brain/> <div><b>AIDEOM-VN</b><span>Đinh Thị Diễm Quỳnh</span></div></div><div className="lesson-list">{lessons.map((l,i)=><button key={l.id} className={selected===l.id?'active':''} onClick={()=>setSelected(l.id)}><BookOpen size={16}/><div><b>Bài {i+1}</b><span>{l.title.replace(/^Bài \d+\s*-\s*/,'')}</span></div></button>)}</div></aside><main><section className="hero"><div><p className="eyebrow">{online?'Module':'Demo fallback'} · {lesson?.module}</p><h1>{lesson?.title}</h1><p>{lesson?.description}</p></div><div className="hero-icon"><Brain size={54}/></div></section><div className="layout"><section className="content"><div className="tabs">{TABS.map(([k,label,Icon])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><Icon size={17}/>{label}</button>)}</div><TabContent tab={tab} result={result}/></section><Params lesson={lesson} params={params} setParams={setParams} onRun={run} loading={loading}/></div></main></div> }

createRoot(document.getElementById('root')).render(<App/>);
